### ISSUE TITLE
Why is that apex doesn't provide wheel for simplicity?

### ISSUE THREAD

**Issue by serser** [NVIDIA/apex#1009]
After seeing so many complaints about version incompatibility and installation troubles, why is that a simple,

`pip install apex` 

still not supported?

**Comment by mcarilli** [comment]
All generally useful tools and optimizations in Apex have been, or are being, moved into mainstream Pytorch.  Maintaining separate pip wheels would be a step in the opposite direction.

**Comment by carmocca** [comment]
I understand the reasoning, however, the active development (see commit activity) also suggests that the package will not be archived soon.

I would greatly appreciate it if this decision was reconsidered given the number of users experiencing installation problems and all the libraries which integrate Apex and experience breaking changes due to the lack of releases or stable versions.

Thank you!
