### ISSUE TITLE
repeat after overflow, not skip?

### ISSUE THREAD

**Issue by jshanna100** [NVIDIA/apex#114]
When using dynamic scaling, could there be an option where the scaling is adjusted on the same batch, until it works, rather than skipping altogether?

I suspect this skipping behaviour is causing fatal instabilities in my GAN training, where one network overflows, and the other doesn't, which leads to the one which doesn't overflow gaining an insurmountable advantage over the other network.

**Comment by mcarilli** [comment]
Yeah, this is definitely a good option to have.  The tricky part is, it requires some control flow outside the optimizer and loss.backward() calls, because the data batch is created and the forward pass is run outside of those.  Long term this may require an API that hands Amp a closure that can replay a user-defined forward pass with the same input data.

In the meantime, such behavior can probably be rigged with user-side control flow, by checking whether Amp detected an overflow state.  Amp implements batch skipping by patching the optimizer.step method, so I believe the following should work:  
```
for batch in batches:
    replay_batch = True
    while replay_batch:
        loss = <your forward pass here, using batch>
        default_optimizer_step = optimizer.step
        with amp_handle.scale_loss(loss, optimizer) as scaled_loss:
            scaled_loss.backward()
        if optimizer.step is default_optimizer_step:
            replay_batch = False
        optimizer.step()
```
I'll try it in a full script (don't hesitate to keep reminding me because I tend to have a lot of input streams)

**Comment by jshanna100** [comment]
Yeah, in the meantime I had implemented a temporary solution where, before the discriminator/generator pass is run, it checks the .overflow parameter of the opposing network optimizer. If positive, it skips, thereby going directly back to the network which overflowed. That prevents one network from getting more iterations than another.

**Comment by mcarilli** [comment]
Added batch replay to our tracker for the API update.  Reopen this if the existing workaround fails for your use case.

**Comment by yuribd** [comment]
Hello @mcarilli, afraid doesn't work in my case https://github.com/NVIDIA/apex/issues/26#issuecomment-458154448

**Comment by mcarilli** [comment]
What's your case?  Are you trying to run [my example](https://gist.github.com/mcarilli/f6dc2b1ab5fc4af1990ea02b731ed692) directly, or are you trying to implement it in a GAN?

Batch replay is intended specifically to help with GANs (i suppose in general it's helpful for any network that has multiple optimizers that need to stay in lockstep, but other than GANs I'm not aware of common cases).   If you're not running a GAN, you should be able to train with Amp's default mode of operation (skipping batches when it encounters overflows) without having to write additional user-side code.

**Comment by yuribd** [comment]
> Are you trying to run my example directly, or are you trying to implement it in a GAN?

Pretty much your code but for my (toy) fully connected feed-forward net. And get: https://github.com/NVIDIA/apex/issues/26#issuecomment-458154448

> you should be able to train with Amp's default mode of operation (skipping batches

Absolutely, but then results are fairly different from single precision raining (without amp) and that's very inconvenient (for number of reasons).

**Comment by yuribd** [comment]
{quote}
Absolutely (as mentioned it works using `FP16_Optimizer `),
{quote}

It does work using `FP16_Optimizer ` but in fact does *not* work using amp even when i skip batches.
```python
  File "/opt/anaconda3/lib/python3.7/site-packages/apex/amp/handle.py", line 55, in scale_loss
    optimizer.param_groups, loss_scale)
  File "/opt/anaconda3/lib/python3.7/site-packages/apex/amp/scaler.py", line 38, in unscale_and_update
    1. / scale)
ZeroDivisionError: float division by zero
```

**Comment by mcarilli** [comment]
That's strange, amp should be strictly >= FP16_Optimizer in terms of stability.  Can you post your toy model?

**Comment by yuribd** [comment]
Sorry, see the issue. Forgot to comment out `model.half()` when switched from `FP16_Optimizer` to `amp`
`amp `works OK, if we don't do `model.half()`, but much slower than fp32 training.  It's the same case (very slow) for `FP16_Optimizer` *with* `dynamic_loss_scale=False`, though switching it off makes things a lot faster (faster than fp32, as it should be)

**Comment by mcarilli** [comment]
Yes, for FP16_Optimizer, you do need to say model.half(), while for amp, you shouldn't.  I'm working on a unified API right now that won't require you to make that change manually.

You could try FP16_Optimizer with a static loss scale (static_loss_scale=128 is a reasonable value) instead of a dynamic loss scale, this tends to be faster.  See if this improves your accuracy.

The fact that amp is slower than fp32 training, and the fact that dynamic loss scaling slows down your application by a lot, makes me think your toy model is likely underutilizing the device.  A small network won't be likely to show much speedup going to fp16.  If you want to investigate performance, the "0th-order" rules of thumb are 1. a big network that saturates the device 2. Gemm dimensions that are multiples of 8, so that tensor cores can be used.  If you're using cudnn 7.1 or earlier (`torch.backends.cudnn.version()`) convolution channel dimensions should also be multiples of 8.

**Comment by yuribd** [comment]
`1. a big network that saturates the device 2. Gemm dimensions that are multiples of 8, so that tensor cores can be used`

Thanks, @mcarilli 

Yes, I'm using multiples of 8 (and it speed ups things a lot)
And FP16 without dynamic scale is *lot faster* (~2x), so net is not so toy. Basically according to documentation `dynamic_loss_scale=True` should make things slower by 10% or so (compared to static), while in practice (in my case) difference is just huge. 

One possible reason i can think of would be it makes sync (between cpu and gpu)? As performance is relying (i.e. lot better) on GPU and CPU being async (in addition to certain operations on GPU being async - running in separate streams)

**Comment by jshanna100** [comment]
Just want to mention that I needed to use "default_optimizer_step == optimizer.step" instead of "default_optimizer_step is optimizer.step"

I didn't look into it, but I presume this has to do with my using multiple loss_ids.
