### ISSUE TITLE
GCC failed with --cuda_ext

### ISSUE THREAD

**Issue by kayuksel** [NVIDIA/apex#136]
I guess that this error is already mentioned but I am unable to install with the --cuda_ext option due to the following isse (torch/extension.h is not found). I should be building with cuda 9.0 or 9.2, having PyTorch version 0.4.0 or 0.4.1

```
gcc -pthread -B /anaconda/envs/py35/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda/envs/py35/lib/python3.5/site-packages/torch/lib/include -I/anaconda/envs/py35/lib/python3.5/site-packages/torch/lib/include/TH -I/anaconda/envs/py35/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/anaconda/envs/py35/include/python3.5m -c apex/optimizers/csrc/fused_adam_cuda.cpp -o build/temp.linux-x86_64-3.5/apex/optimizers/csrc/fused_adam_cuda.o -O3 -DTORCH_EXTENSION_NAME=fused_adam_cuda -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
apex/optimizers/csrc/fused_adam_cuda.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by mcarilli** [comment]
The C++/Cuda extension API was not stable prior to pytorch 1.0, and we don't officially support it for versions prior to 1.0.  I recommend that you run in a docker container (either one of ours, or upstream, as described in https://github.com/NVIDIA/apex/issues/112#issuecomment-453307010).  Substitute nightly-devel-cuda9.2-cudnn7 instead of cuda10.0 if needed.
