### ISSUE TITLE
Got unexpected keyword argument 'channel_last' when using apex.parallel.convert_syncbn_model

### ISSUE THREAD

**Issue by hubutui** [NVIDIA/apex#166]
As https://github.com/NVIDIA/apex/blob/b2f63c48408e1110bb1c7ad7bf6310141da30616/apex/parallel/__init__.py#L41 shows, `apex.parallel.convert_syncbn_model` pass `channel_last` to `SyncBatchNorm`, but `SyncBatchNorm` does not accept. I'm not sure why this function adds a `channel_last` keyword, PyTorch uses channel first tensor, while TensorFlow uses channel last. Simply remove channel_last from the function call fix this issue.

**Comment by jjsjann123** [comment]
I should have done a better job maintaining the API 😭 

channel_last flag is supported by our optimized BN implementation (Requires installation with `--cuda_ext`). You are encouraged to use the optimized version as it provides better perf with fused kernels.

I'll update the primitive op implementation so that it accepts this dummy argument. (as suggested by @egaburov)
