### ISSUE TITLE
cuFFT in FP16, O2 optimization and patch_torch_functions

### ISSUE THREAD

**Issue by nikitamoriakov** [NVIDIA/apex#271]
Hi all, I am trying to use APEX for training a model that needs to perform fft on data with dimensions that are potentially not powers of two. Currently cuFFT doesn't support this operation for FP16, only for FP32.

In order to 'fix' this I added fft to the list of FP32 functions and then tried to pass an extra argument patch_torch_functions=True to the apex initializer with optimization level O2. What I get is an error message saying that this is not allowed with O2 optimization:
```
 model, optimizer = amp.initialize(model, optimizer, opt_level=opt_level, patch_torch_functions=True)
File "/home/miniconda3/lib/python3.7/site-packages/apex/amp/frontend.py", line 299, in initialize
_amp_state.opt_properties.patch_torch_functions = patch_torch_functions
File "/home/miniconda3/lib/python3.7/site-packages/apex/amp/frontend.py", line 65, in __setattr__
warn_or_err("Currently, patch_torch_functions=True should only be set by "
File "/home/miniconda3/lib/python3.7/site-packages/apex/amp/_amp_state.py", line 31, in warn_or_err
raise RuntimeError(msg)
RuntimeError: Currently, patch_torch_functions=True should only be set by selecting opt_level='O1'.
```
Is there a workaround for this problem? Or does it need substantial code changes?

**Comment by ptrblck** [comment]
Hi @nikitamoriakov,

are you using a custom module which is applying the cuFFT operation?
If so, I assume you've derived the class from `nn.Module` and implemented the forward (and backward) pass manually.
Is CUDA throwing an error is you pass FP16 inputs to the method?

Here is a workaround, in case you need a working approach now, but note that these changes are quite a hack and might break in future releases. If you could provide some more information, we would be happy to provide a proper solution to this problem. :)

If this module contains learnable parameters, which should stay in FP32, a quick fix could be to add your custom module to the if-condition in `convert_network` so that it will stay in FP32 in [this line of code](https://github.com/NVIDIA/apex/blob/1c464b48472e32bdb752f77815502bffe0acd284/apex/fp16_utils/fp16util.py#L65). Alternatively, you could cast the parameters manually to `float()` and back to `half()` in your `forward()` method, which might decrease the performance depending on the size of the parameters.
Here is a small example using the "slower" approach without adding your custom module to `convert_network`:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F

from apex import amp


class MyFP32Module(nn.Module):
    def __init__(self):
        super(MyFP32Module, self).__init__()
        self.param = nn.Parameter(torch.randn(1, dtype=torch.float32))

    def forward(self, x):
        x = x.float() + self.param.float()
        return x.half()


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.lin1 = nn.Linear(10, 10)
        self.bn1 = nn.BatchNorm1d(10, affine=True)
        self.fp32module = MyFP32Module()
        
        self.lin2 = nn.Linear(10, 1)
        
    def forward(self, x):
        x = self.lin1(x)
        x = self.bn1(x)
        x = F.relu(self.fp32module(x))
        x = self.lin2(x)
        return x


model = MyModel()
model = model.to('cuda')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

model, optimizer = amp.initialize(model, optimizer, opt_level='O2')

x = torch.randn(2, 10, device='cuda')
output = model(x)
```

@mcarilli Would it be a good idea to allow users to pass a custom list of modules which should not be converted?

**Comment by nikitamoriakov** [comment]
Hi @ptrblck,

Thanks for the advice! I need to call `torch.fft` and `torch.ifft` in a forward pass of a module, and ensure that it works with data of non-power-of-two dimensions. So I am now doing the following quick fix:
`target = torch.ifft(source.float(), 2).type(source.type()) `
This works fine with O2 optimization and gives me the memory savings I want. 

Am I correct assuming that APEX with O2 optimization casts module inputs to FP16 but doesn't trap function calls? I remember that certain functions such as `torch.softmax` were marked as FP32-only in O1 mode for numerical precision reasons, so how does work with O2?

**Comment by ngimel** [comment]
You are correct, O2 does not trap function calls. O2 relies on the user to do all the necessary casts, so absent any action from the user, torch.softmax will be in fp16 with O2 optimization mode.

**Comment by nikitamoriakov** [comment]
Thank you! 

I would say that the question is closed.
