### ISSUE TITLE
Performance with NVLink

### ISSUE THREAD

**Issue by SergeyMilyaev** [NVIDIA/apex#282]
Hi everyone, we started testing 2080ti with Quadro NVLink bridge. We have a machine with 4 2080ti GPU cards. We connected the cards 2 and 3 with the NVLink bridge, while the cards 0 and 1 were left without bridge connection.
The output of nvlink status shows that everything is fine

```
nvidia-smi nvlink --status -i 2
GPU 2: GeForce RTX 2080 Ti (UUID: GPU-6c41afdf-d8aa-ed9b-24a2-fa90c471fda0)
	 Link 0: 25.781 GB/s
	 Link 1: 25.781 GB/s
```

```
nvidia-smi nvlink --status -i 3
GPU 3: GeForce RTX 2080 Ti (UUID: GPU-a78f4e04-05cc-74fe-5d3a-c2ad0f069e05)
	 Link 0: 25.781 GB/s
	 Link 1: 25.781 GB/s
```
I also checked p2p connectivity, its output below also seems to be fine.
[p2p_test.txt](https://github.com/NVIDIA/apex/files/3133288/p2p_test.txt)

Then I made slight modifications to the [PyTorch ImageNet example](https://gist.github.com/SergeyMilyaev/b535d2f5bf57dda7cdbc2941b2540dc6) and [Apex ImageNet example](https://gist.github.com/SergeyMilyaev/156135e0949a5e648e01686b4cc85538), so that they use random input instead of ImageNet data.

I decided to run 4 tests:

- Test 1, PyTorch DataParallel with ResNet18: python main.py dummy
- Test 2, PyTorch DistributedDataParallel with ResNet18: python main.py dummy --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --dist-url 'tcp://127.0.0.1:2504' dummy
- Test 3, Apex FP32 training: python main_amp.py -a resnet50 --b 64 --workers 4 --opt-level O0 dummy
- Test 4, Apex FP16 training: python main1_amp.py -a resnet50 --b 64 --workers 4 --opt-level O2 dummy

As a result of time measurements for batch processing I took the output of a time per batch running average at the end of the first training epoch in each test. Tests with NVLink were run on cards 2 and 3, tests without NVLink - on cards 0 and 1.
While for the Test 1 a batch processing time reduced with NVLink from 0.190 to 0.182 seconds and for the Test 2 from 0.172 to 0.166 seconds, for Test 3 NVLink connection increased a batch processing time from 0.249 to 0.278 seconds and for Test 4 from 0.172 to 0.202 seconds.
Does anybody observed the similar performance drop with using NVLink and Apex together or could suggest more appropriate performance tests?

**Comment by mcarilli** [comment]
That's strange.  We run with nvlink all the time and it's fine, much faster than standard PCIE connections.  Those Apex commands aren't running distributed training at all, I don't think.  You need to launch via
```
export CUDA_VISIBLE_DEVICES=2,3
# Test 3
python -m torch.distributed.launch --nproc_per_node=2 main_amp.py -a resnet50 --b 64 --workers 4 --opt-level O0 dummy
# Test 4
python -m torch.distributed.launch --nproc_per_node=2 main1_amp.py -a resnet50 --b 64 --workers 4 --opt-level O2 dummy
```
Typically setting CUDA_VISIBLE_DEVICES is not necessary (each process simply sets a device based on its --local_rank, which is appended to the argument list by the torch.distributed.launch wrapper).  CUDA_VISIBLE_DEVICES is helpful here because you want to explicitly control which GPUs the processes run on.  Maybe you were doing all this already, and it's implicit in your message above.

By the way batch size 64 is probably too small to achieve ideal utilization (although it's fine for testing in this case).  Using batch size 128 for FP32 (O1) or batch size 224 or even 256 for mixed precision (O1 and O2) will do a better job of saturating the device and reduce end-to-end training time.

**Comment by SergeyMilyaev** [comment]
@mcarilli , thank you for the reply. In my evaluations I used CUDA_VISIBLE_DEVICES , but I forgot to add the arguments you specified for distributed training.
For Test 3 with Apex and FP32 I increased the batch size to 96 and got 0.4 s. per batch for the cards 0,1 (without NVLink) and 0.375 s. for the cards 2,3 with NVLink.
For Test 4 with Apex and FP16 I increased the batch size to 192 and got 0.463 s. per batch for the cards 0,1 (without NVLink) and 0.454 s for the cards 2,3 with NVLink.
Now I see speedup for Apex with NVLink, although for FP16 it's smaller.
Also, it would be interesting to see what speedups do you observe with Apex and NVLink and the hardware you use.

**Comment by mcarilli** [comment]
Good!  The batch size numbers I quoted were for a V100 with 16GB of onboard memory, so for your 2080Tis with (I believe) 11GB of onboard memory, the batch sizes you are using for FP32 and mixed precision are likely achieving decent saturation.

Typically I work on systems like 
- DGXs where everything is connected via nvlink, 
- DGX2s where everything is connected via nvswitch, or 
- minimal desktop setups with no nvlink.  

I don't have access to a setup like yours where it's possible to get an apples to apples comparison of nvlink versus no nvlink.  I think the speedup it's delivering in your case is reasonable, given that for a 2-GPU job the comms are probably a smallish fraction of each iteration's runtime.  For Test 4 (training with O2) the data that's being allreduced is (mostly) FP16, so the total amount of time and probably the fraction of per-iteration time spent in comms is reduced, so it's sensible to me that nvlink has less of a positive impact for Test 4 than it does for Test 3 (FP32). 

It's difficult to predict exactly what speedup nvlink will deliver, because this depends on ratio of comms to compute time within each device (which depends on the network, individual bandwidth/computational horsepower within each device, per-device batch size, and number of total processes/GPUs in the job), but it should always be better than PCIE.  In general, the more GPUs your job uses (within a node), the more helpful nvlink becomes.

**Comment by SergeyMilyaev** [comment]
@mcarilli , thank you for the provided answers!

**Comment by FlorinAndrei** [comment]
@SergeyMilyaev Do you have a code example with PyTorch where it uses multiple GPUs with NVLink?

Or, if that's not the case, what would you modify to this example so that it uses multiple GPUs with NVLink?

https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

Thanks!

**Comment by SergeyMilyaev** [comment]
@FlorinAndrei there is no special code for running training on multiple GPUs with NVLink. You can use my [DataParallel example](https://gist.github.com/SergeyMilyaev/b535d2f5bf57dda7cdbc2941b2540dc6) or [Apex example](https://gist.github.com/SergeyMilyaev/156135e0949a5e648e01686b4cc85538). Just be sure, that for the connected with NVLink cards the output of the command 'nvidia-smi nvlink' confirms that the NVLink is enabled as you can see in my [original post](https://github.com/NVIDIA/apex/issues/282#issue-439007428).

**Comment by FlorinAndrei** [comment]
@SergeyMilyaev To make sure, with the DataParallel example, if you have 2 hosts with 4 GPUs each, will this train a single model on all GPUs at once?

```
python3 test.py . --epochs 10 --multiprocessing-distributed --world-size 2 --rank 0 \
    --dist-url 'tcp://0.0.0.0:9999'

python3 test.py . --epochs 10 --multiprocessing-distributed --world-size 2 --rank 1 \
    --dist-url 'tcp://${THE_OTHER_HOST}:9999'
```

**Comment by SergeyMilyaev** [comment]
@FlorinAndrei, don't use in general --multiprocessing-distributed. For effective multi-node/multi-GPU training please check [torch.distributed|https://pytorch.org/docs/stable/distributed.html].
