### ISSUE TITLE
How can I force a user defined function to running in FP32 with opt_level O1?

### ISSUE THREAD

**Issue by roominforest** [NVIDIA/apex#293]
Hi! @mcarilli. Thank you for your excellent work for training with fp16 method. But I have some questions when I use it with opt_level O1 in my recent work.
    The first thing I want to know is whether opt_level O1 means all the weights are kept in fp32 while running (by the means of handle in code,I suppose) in fp16 or fp32 according to the white list and black list.
    Secondly, how the opt_level O1 guarantees all the operations and all the parameters in batchnorm kept in fp32 ? 
   Last but not the least, I wonder if a user defined function will be running in fp16 by default with opt_level O1. And if so, how can I force it running in fp32 with opt_level O1?
   I will be grateful for your reply!

**Comment by mcarilli** [comment]
Yes, with opt_level O1, all the parameters (and buffers like batchnorm stats) are kept in FP32.  Batchnorm does not receive any special casting treatment different, it simply processes whatever activations inputs it is given, using its FP32 weights and buffers.

The activations may change type as they flow through the network.  For example, whenever they encounter a Tensor Core op like a GEMM or convolution, the activations are cast to FP16, and the outputs of such ops are sent along as FP16.  I believe the actual batchnorm kernel is occasionally run in fp16, depending on what type the input activations happen to be at that point.  With O1, these are the possibilities for batchnorm:
1. FP32 weights+buffers + FP16 activation input = FP16 kernel and FP16 output
2. FP32 weights+buffers + FP32 activation input = FP32 kernel and FP32 output

However, the FP16 kernel is a cudnn kernel that is designed to be stable in FP16, so possibility 1. is not dangerous imo, unless you are seeing otherwise? 

Amp has no way to anticipate that user-defined functions exist, so by default, user-defined functions will not be patched to cast their inputs.  They will simply process inputs in whatever type the inputs are given by the previous op.  However, you can explicitly register a user-defined function to always cast inputs to a particular type:
https://github.com/NVIDIA/apex/tree/master/apex/amp#annotating-user-functions

Beware, that README is out of date.  The `Annotating User Functions` section is still correct, but everything outside that section should be ignored.

I'm going to close this, please reopen if the suggestions don't help your use case.
