### ISSUE TITLE
Does apex needs GPU with Tensor Core architecture? 

### ISSUE THREAD

**Issue by hackerekcah** [NVIDIA/apex#324]
1. Does apex needs GPU with Tensor Core architecture? 
2. I use Tesla K40, is it Tensor Core architecture? Can I use apex to speed up training?

**Comment by ptrblck** [comment]
Hi @hackerekcah,

1. No, you can use apex with any GPU which uses CUDA9 or newer. Note that the PyTorch binaries ship with pre-built CUDA libs, which should match your CUDA system install.

2. Unfortunately not, since the Tesla K40 is based on the Kepler architecture. GPUs based on the Volta and Turing architecture should accelerate mixed-precision training. However, you could still use `apex` to e.g. potentially lower the memory usage on your GPU.

**Comment by hackerekcah** [comment]
Thanks!
