### ISSUE TITLE
Why the caching logic only happens at FP32->FP16 cast?

### ISSUE THREAD

**Issue by kingder** [NVIDIA/apex#327]
The utils.should_cache(x) returns true only when x is 'FloatTensor', it seems to me the cache only applies to fp32->fp16 cast, what about the other way around?

**Comment by mcarilli** [comment]
The cache is only used when `opt_level="O1"`, because that's when you're casting inputs to functions on the fly, so if you have a particular weight that's used in multiple fp16/Tensor Core-friendly functions in the forward pass, Amp only needs to carry out that cast once, and can reuse the cached (fp16-casted) version of the weight for other fp16-friendly functions that use the same weight.

This caching-of-casts is only used for weights (leaves/Parameter attributes of models), and with O1, the weights are always stored as FP32 (then potentially casted as they enter fp16-friendly functions).  Therefore, the only kind of cast we would need to cache is an FP32->FP16 cast.

If we implemented caching of casts for internal activations as well, it might be beneficial to cache FP16->FP32 casts.  However, the internal activations are temporaries.  If a given FP16 temporary is cast to FP32 for some FP32 operation, and that FP32 cast is cached, but the temporary is never reused (and the FP32 op did not require that its input to be saved for the backward pass) then the FP32 cached cast is being kept around for no reason, and wasting memory.

Caching casts only for weights, and not caching casts for internal temporaries, seemed like a reasonable balance between performance and memory usage.  Since we only cache casts for weights, we only need to cache fp32->fp16 casts.
