### ISSUE TITLE
pytorch grid sampler error

### ISSUE THREAD

**Issue by buoyancy99** [NVIDIA/apex#375]
I was running apex.amp on a module with torch.nn.functional.grid_sample and it gave me this error

RuntimeError: grid_sampler(): expected input and grid to have same dtype, but input has float and grid has c10::Half

**Comment by mcarilli** [comment]
grid_sample takes 2 inputs, which must match.  Hopefully fixed by https://github.com/NVIDIA/apex/commit/656d14b0c9792a1bcdc255b473dc2d6145d026ff.  I'm making it an FP32 function for now in case some of the backward kernels use atomics, which are slow in FP16.

In general we find such functions by experience, so thanks for bringing this to our attention.

**Comment by rubencart** [comment]
Still getting this error
