### ISSUE TITLE
TypeError: OptimWrapper is not an Optimizer

### ISSUE THREAD

**Issue by carbonox-infernox** [NVIDIA/apex#54]
Hello,

I have tried to implement amp by wrapping a pre-existing model:

https://github.com/neptune-ml/open-solution-mapping-challenge

I've scoured the source code and am pretty sure there is only one optimizer, so I first tried enabling amp and wrapping backpropagation as instructed, but after that training ran only about 75-80% as fast as it had before. So I decided to try explicitly wrapping the optimizer:

        self.optimizer = optim.Adam(self.weight_regularization(self.model, **architecture_config['regularizer_params']),
                                    **architecture_config['optimizer_params'])
        #Initializing amp
        amp_handle = amp.init()
        #Wrapping self.optimizer
        self.optimizer = amp_handle.wrap_optimizer(self.optimizer)
        self.loss_function = None
        self.callbacks = callbacks_unet(self.callbacks_config)

And then at the backdrop:

        with self.optimizer.scale_loss(batch_loss) as scaled_loss:
            scaled_loss.backward()
        self.optimizer.step()

However, I get the following error:

2018-10-10 17-24-18 steps >>> step unet fitting and transforming...

Traceback (most recent call last):

  File "main.py", line 93, in <module>

    main()

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "main.py", line 31, in train

    pipeline_manager.train(pipeline_name, dev_mode)

  File "/ebs/osmc/src/pipeline_manager.py", line 32, in train

    train(pipeline_name, dev_mode, self.logger, self.params, self.seed)

  File "/ebs/osmc/src/pipeline_manager.py", line 116, in train

    pipeline.fit_transform(data)

  File "/ebs/osmc/src/steps/base.py", line 106, in fit_transform

    step_inputs[input_step.name] = input_step.fit_transform(data)

  File "/ebs/osmc/src/steps/base.py", line 106, in fit_transform

    step_inputs[input_step.name] = input_step.fit_transform(data)

  File "/ebs/osmc/src/steps/base.py", line 106, in fit_transform

    step_inputs[input_step.name] = input_step.fit_transform(data)

  [Previous line repeated 3 more times]

  File "/ebs/osmc/src/steps/base.py", line 112, in fit_transform

    return self._cached_fit_transform(step_inputs)

  File "/ebs/osmc/src/steps/base.py", line 123, in _cached_fit_transform

    step_output_data = self.transformer.fit_transform(**step_inputs)

  File "/ebs/osmc/src/steps/base.py", line 262, in fit_transform

    self.fit(*args, **kwargs)

  File "/ebs/osmc/src/models.py", line 76, in fit

    self.callbacks.set_params(self, validation_datagen=validation_datagen, meta_valid=meta_valid)

  File "/ebs/osmc/src/steps/pytorch/callbacks.py", line 76, in set_params

    callback.set_params(*args, **kwargs)

  File "/ebs/osmc/src/steps/pytorch/callbacks.py", line 222, in set_params

    self.lr_scheduler = ExponentialLR(self.optimizer, self.gamma, last_epoch=-1)

  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 178, in __init__

    super(ExponentialLR, self).__init__(optimizer, last_epoch)

  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 13, in __init__

    type(optimizer).__name__))

TypeError: OptimWrapper is not an Optimizer

Did I make a stupid mistake somewhere? Did i forget to do something? Or is something about this model incompatible with apex?

**Comment by mcarilli** [comment]
As far as I know the OptimWrapper buried in Amp is not meant to be used standalone.  If you wish to use a standalone optimizer wrapper, we have a separate tool for that:  https://github.com/NVIDIA/apex/tree/master/examples/FP16_Optimizer_simple

Note that FP16_Optimizer does not do anything to the Torch namespace, so you have to control what runs in half precision.  Specifically, you must call `.half()` on your model and data (which is NOT something you need to do when running amp.).

If you want batchnorms to run in FP32, instead of `model.half()` you can say
`model = apex.fp16_utils.network_to_half(model)` as shown in [our Imagenet example](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main.py#L123).

Make sure you do things in the following order:
1.  Cast model to half using `model = network_to_half(model)` or `model.half()`
2.  Construct Pytorch optimizer from model parameters
3.  Construct FP16_Optimizer to wrap the Pytorch optimizer.

**Comment by carbonox-infernox** [comment]
@mcarilli Thanks! I'm a noob at python, pytorch, neural nets, etc so it will take me a while to process this.

I am confused that you said "the OptimWrapper buried in Amp is not meant to be used standalone." Can you elaborate on this? I just followed the instructions for using amp here: 

https://github.com/NVIDIA/apex/tree/master/apex/amp 

and it seemed to me that I was using Amp for the purpose it was designed for. What else should I do with amp if I have not done enough?

**Comment by mcarilli** [comment]
Ah you're right, it's intended to be used that way when you have multiple optimizers, so likely it should work fine when using a single optimizer as well (@carlc-nv can you confirm)?  

I think the problem you're observing is because Pytorch learning rate schedulers (in e.g. torch/optim/lr_scheduler.py) [explicitly check](https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L12-L14) if the object they're operating on inherits from `torch.optim.Optimizer`, and it appears the wrapped optimizer does not.  

Regardless, I don't think explicitly wrapping your optimizer would affect the speed with amp.  For performance analysis, the first thing I would try is simply "pure FP16" training:  Don't bother with any Apex tools, just convert your model to `.half()` and run blindly.  This may be numerically unsafe, but it will establish a baseline of how much speedup is available by switching to FP16.

In the past, we have observed that for some networks pure FP16 training can be slow.  If so, the root cause is unrelated to the mixed precision recipe applied by Apex.   Perhaps device utilization is low, or you hit some pathologic edge cases in cudnn or cublas.  We can provide additional guidance along those lines.

If you find that pure FP16 training runs fast, and then once you turn on Amp or FP16_Optimizer, the network becomes slow again, then we know Apex is likely the culprit, and we can debug along those lines instead.

**Comment by carbonox-infernox** [comment]
@mcarilli Thanks for the advice!

Sorry to be such a noob, but how would I go about converting my model to .half()? Do I replace .cuda() with .half()?

**Comment by mcarilli** [comment]
No, those are orthogonal.  .cuda() puts your model parameters and buffers on the GPU.  .half() converts them to FP16.  So you'll need to do both:
`model.cuda().half()`
