### ISSUE TITLE
warning: integer conversion resulted in a change of sign

### ISSUE THREAD

**Issue by BramVanroy** [NVIDIA/apex#541]
Building apex on my system (Ubuntu 18.04) is successfull, but the building process is full of the following warning

>  warning: integer conversion resulted in a change of sign

I don't know anything about C++, but I would imagine that if in math the sign is changed unexpectedly, that could have grave consequences.

**Comment by mcarilli** [comment]
The same warning appears when I compile the torch cpp extension tests
```
$ cd pytorch_repo/test/cpp_extensions
$ python setup.py install
```
The first few extensions, compiled with gcc, do not show the warning, but two later extensions, compiled with nvcc, do show the warning.

So I don't think this has to do with apex and it doesn't appear to affect the operation.  In fact, looking at the [pytorch source where the warning comes from](https://github.com/pytorch/pytorch/blob/master/c10/core/TensorTypeSet.h#L43-L44), it may be a deliberate hack to set repr_ to all 1s, since repr_ is an unsigned integer, and nvcc is being pedantic about warning us.

**Comment by AlyssaYoung** [comment]
I also met this problem when I built apex on my system(Ubuntu 18.04), but the process were not successful. The warning message appearred all the time. How can I solve this problem?
