### ISSUE TITLE
How to convert O1 initialized Pytorch Model back to float precision for evaluation?

### ISSUE THREAD

**Issue by yzhao520** [NVIDIA/apex#567]
HI,

I'm currently using apex with pytorch to train my model and optim level is set to be ``opt_level="O1"`` during training. I would like to evaluate with float32 precision immediately after training. Is there any way to convert models back to float32 precision? I have tried ``model.float()`` but it seems not working. The model output is still Half type tensor with float type tensor input. 

I'm using pytorch 1.1, apex 0.1 and ubuntu 16.04. Thanks for your help!

**Comment by mcarilli** [comment]
With O1, the model IS fp32 in the sense that the leaves/parameters remain FP32.  The reason you're seeing FP16 output is because after amp.initialize, the autocasting is globally enabled.

If you wish to evaluate in pure fp32, try running under the `disable_casts` context manager:
```
with apex.amp.disable_casts():
    evaluation loop
```

**Comment by mcarilli** [comment]
In the upstream integration of mixed precision, which is currently in progress, the plan is to support autocasting via an opt-_in_ context manager for regions that you'd like to run in mixed precision, instead of an opt-_out_ context manager like `apex.amp.disable_casts()`.  See
https://github.com/pytorch/pytorch/issues/25081 and scroll down to **Auto-casting** if you are curious.

**Comment by yzhao520** [comment]
Thanks for your help, it works! I'll close this issue now.
