### ISSUE TITLE
NotImplementedError: Cannot call in-place method exp_ on fp16 Tensors.

### ISSUE THREAD

**Issue by MrHuff** [NVIDIA/apex#576]
Hi, 

First I'd like to thank you for this fantastic library, it really accelerates my research projects!

I am trying to combine apex with gpytorch and I am getting this error:

NotImplementedError: Cannot call in-place method exp_ on fp16 Tensors.

Presumably exp_ needs to be implemented for fp16 Tensors. I am wondering if you could help me with this?

Thank you!

Best regards,
Robert

**Comment by mcarilli** [comment]
The problem is that it can't handle in-place blacklist ops.  Exponentiation is a blacklist op that may require FP32 dynamic range, so Amp wants to cast the inputs to FP32.  This would mean that the operation is no longer in-place, though, so it errors rather than silently doing something unexpected.  If you use an out of place `exp` instead of `exp_` it should work.

**Comment by MrHuff** [comment]
Alright, I understand!

Thanks!
