### ISSUE TITLE
[Bug]`torch.acos()` will convert float16 to float32 while using Apex.

### ISSUE THREAD

**Issue by PistonY** [NVIDIA/apex#606]
Hello, I found a bug I think.
Using Apex will make `torch.acos()` not work correctly.

Example:
Don't use Apex.
```python
import torch
from torchvision.models.resnet import resnet18

model = resnet18().half().cuda()
model.train()
data =  torch.randint(0, 224, size=(1, 3, 224, 224)).half().cuda()
output = model(data)
cs = torch.acos(output)
print(cs.dtype)
```
The result would be
```shell
torch.float16
```
But while using Apex

```python
import torch
from torchvision.models.resnet import resnet18
from apex import amp
from torch import optim

model = resnet18().cuda()
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9,
                                     weight_decay=1e-4, nesterov=True)

model, optimizer = amp.initialize(model, optimizer, opt_level='O1')
model.train()
data =  torch.randint(0, 224, size=(1, 3, 224, 224)).half().cuda()
output = model(data)
cs = torch.acos(output)
print(cs.dtype)
```
The result would be
```shell
torch.float32
```
Normally an operation should not change data `dtype` I think.
If you don't think that's a bug or my there is something wrong with my code, please tell me how to get a correct(float16) result thanks.

**Comment by PistonY** [comment]
Nobody cares?

**Comment by mcarilli** [comment]
This is the expected behavior.  Under O1, acos is a [blacklist function](https://github.com/NVIDIA/apex/blob/master/apex/amp/lists/torch_overrides.py#L31) that upcasts the inputs to fp32.  In general, all blacklist operations must change the output type to FP32, because the whole point is that output values may not be representable in FP16.  Other operations further down the line will cast back to FP16 if appropriate.

**Comment by PistonY** [comment]
I knew this, thanks for your reply.
