### ISSUE TITLE
ImportError("/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by victornoriega** [NVIDIA/apex#716]
This is a warning and also an error when trying to test a model with a language model using CTC decoder.
I'm using CentOS 7.5
Cuda 10.2
Cudnn 7.6.5

I don't have su, so I installed the decoders dependencies from conda. 

When I run 
`strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX`

I get

`GLIBCXX_3.4

GLIBCXX_3.4.1

GLIBCXX_3.4.2

GLIBCXX_3.4.3

GLIBCXX_3.4.4

GLIBCXX_3.4.5

GLIBCXX_3.4.6

GLIBCXX_3.4.7

GLIBCXX_3.4.8

GLIBCXX_3.4.9

GLIBCXX_3.4.10

GLIBCXX_3.4.11

GLIBCXX_3.4.12

GLIBCXX_3.4.13

GLIBCXX_3.4.14

GLIBCXX_3.4.15

GLIBCXX_3.4.16

GLIBCXX_3.4.17

GLIBCXX_3.4.18

GLIBCXX_3.4.19

GLIBCXX_DEBUG_MESSAGE_LENGTH`

So there's actually no GLIBCXX_3.4.20.

What can I do?

**Comment by wangbo9719** [comment]
It seems like I have the same problems
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ImportError("/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found .

I use commond " pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./  " to install.

I'm using Cuda 10.2 and Linux
